"""AUTO-GENERATED from build_api_wrap.py — do not edit."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from cli_fpp.utils import fpp_backend as api


@dataclass(frozen=True)
class Operation:
    id: str
    method: str
    path: str
    tag: str
    cli_name: str
    summary: str
    path_params: tuple[str, ...]
    query_params: tuple[str, ...]
    mutating: bool


OPERATIONS: dict[str, Operation] = {
    "backups__post-configuration": Operation(
        id="backups__post-configuration",
        method="POST",
        path="/api/backups/configuration",
        tag="backups",
        cli_name="post-configuration",
        summary="Create JSON backup",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "backups__get-configuration-list": Operation(
        id="backups__get-configuration-list",
        method="GET",
        path="/api/backups/configuration/list",
        tag="backups",
        cli_name="get-configuration-list",
        summary="Get available JSON backups",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "backups__get-configuration-list-devicename": Operation(
        id="backups__get-configuration-list-devicename",
        method="GET",
        path="/api/backups/configuration/list/{DeviceName}",
        tag="backups",
        cli_name="get-configuration-list-devicename",
        summary="Get list of JSON backups on device",
        path_params=('DeviceName',),
        query_params=(),
        mutating=False,
    ),
    "backups__post-configuration-restore-directory-backupfilename": Operation(
        id="backups__post-configuration-restore-directory-backupfilename",
        method="POST",
        path="/api/backups/configuration/restore/{Directory}/{BackupFilename}",
        tag="backups",
        cli_name="post-configuration-restore-directory-backupfilename",
        summary="Restores JSON backup",
        path_params=('Directory', 'BackupFilename'),
        query_params=(),
        mutating=True,
    ),
    "backups__delete-configuration-directory-backupfilename": Operation(
        id="backups__delete-configuration-directory-backupfilename",
        method="DELETE",
        path="/api/backups/configuration/{Directory}/{BackupFilename}",
        tag="backups",
        cli_name="delete-configuration-directory-backupfilename",
        summary="Delete JSON backup",
        path_params=('Directory', 'BackupFilename'),
        query_params=(),
        mutating=True,
    ),
    "backups__get-configuration-directory-backupfilename": Operation(
        id="backups__get-configuration-directory-backupfilename",
        method="GET",
        path="/api/backups/configuration/{Directory}/{BackupFilename}",
        tag="backups",
        cli_name="get-configuration-directory-backupfilename",
        summary="Download JSON backup",
        path_params=('Directory', 'BackupFilename'),
        query_params=(),
        mutating=False,
    ),
    "backups__get-devices": Operation(
        id="backups__get-devices",
        method="GET",
        path="/api/backups/devices",
        tag="backups",
        cli_name="get-devices",
        summary="Get devices available for backups",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "backups__post-devices-mount-devicename-mountlocation": Operation(
        id="backups__post-devices-mount-devicename-mountlocation",
        method="POST",
        path="/api/backups/devices/mount/{DeviceName}/{MountLocation}",
        tag="backups",
        cli_name="post-devices-mount-devicename-mountlocation",
        summary="Mount device",
        path_params=('DeviceName', 'MountLocation'),
        query_params=(),
        mutating=True,
    ),
    "backups__post-devices-unmount-devicename-mountlocation": Operation(
        id="backups__post-devices-unmount-devicename-mountlocation",
        method="POST",
        path="/api/backups/devices/unmount/{DeviceName}/{MountLocation}",
        tag="backups",
        cli_name="post-devices-unmount-devicename-mountlocation",
        summary="Unmount device",
        path_params=('DeviceName', 'MountLocation'),
        query_params=(),
        mutating=True,
    ),
    "backups__get-list": Operation(
        id="backups__get-list",
        method="GET",
        path="/api/backups/list",
        tag="backups",
        cli_name="get-list",
        summary="Get available backups",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "backups__get-list-devicename": Operation(
        id="backups__get-list-devicename",
        method="GET",
        path="/api/backups/list/{DeviceName}",
        tag="backups",
        cli_name="get-list-devicename",
        summary="Get list of backups on device",
        path_params=('DeviceName',),
        query_params=(),
        mutating=False,
    ),
    "cape__get-cape": Operation(
        id="cape__get-cape",
        method="GET",
        path="/api/cape",
        tag="cape",
        cli_name="get-cape",
        summary="Get cape information",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "cape__post-eeprom-sign-key-order": Operation(
        id="cape__post-eeprom-sign-key-order",
        method="POST",
        path="/api/cape/eeprom/sign/{key}/{order}",
        tag="cape",
        cli_name="post-eeprom-sign-key-order",
        summary="Sign EEPROM",
        path_params=('key', 'order'),
        query_params=(),
        mutating=True,
    ),
    "cape__post-eeprom-signingdata": Operation(
        id="cape__post-eeprom-signingdata",
        method="POST",
        path="/api/cape/eeprom/signingData",
        tag="cape",
        cli_name="post-eeprom-signingdata",
        summary="Upload signed EEPROM",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "cape__get-eeprom-signingdata-key-order": Operation(
        id="cape__get-eeprom-signingdata-key-order",
        method="GET",
        path="/api/cape/eeprom/signingData/{key}/{order}",
        tag="cape",
        cli_name="get-eeprom-signingdata-key-order",
        summary="Get signing data as text",
        path_params=('key', 'order'),
        query_params=(),
        mutating=False,
    ),
    "cape__get-eeprom-signingfile-key-order": Operation(
        id="cape__get-eeprom-signingfile-key-order",
        method="GET",
        path="/api/cape/eeprom/signingFile/{key}/{order}",
        tag="cape",
        cli_name="get-eeprom-signingfile-key-order",
        summary="Get signing data as binary",
        path_params=('key', 'order'),
        query_params=(),
        mutating=False,
    ),
    "cape__post-eeprom-voucher": Operation(
        id="cape__post-eeprom-voucher",
        method="POST",
        path="/api/cape/eeprom/voucher",
        tag="cape",
        cli_name="post-eeprom-voucher",
        summary="Redeem signing voucher",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "cape__get-options": Operation(
        id="cape__get-options",
        method="GET",
        path="/api/cape/options",
        tag="cape",
        cli_name="get-options",
        summary="Get cape options",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "cape__get-panel": Operation(
        id="cape__get-panel",
        method="GET",
        path="/api/cape/panel",
        tag="cape",
        cli_name="get-panel",
        summary="Get all cape panels",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "cape__get-panel-key": Operation(
        id="cape__get-panel-key",
        method="GET",
        path="/api/cape/panel/{key}",
        tag="cape",
        cli_name="get-panel-key",
        summary="Get cape panel",
        path_params=('key',),
        query_params=(),
        mutating=False,
    ),
    "cape__get-strings": Operation(
        id="cape__get-strings",
        method="GET",
        path="/api/cape/strings",
        tag="cape",
        cli_name="get-strings",
        summary="Get all cape strings",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "cape__get-strings-key": Operation(
        id="cape__get-strings-key",
        method="GET",
        path="/api/cape/strings/{key}",
        tag="cape",
        cli_name="get-strings-key",
        summary="Get cape string",
        path_params=('key',),
        query_params=(),
        mutating=False,
    ),
    "channel__delete-input-stats": Operation(
        id="channel__delete-input-stats",
        method="DELETE",
        path="/api/channel/input/stats",
        tag="channel",
        cli_name="delete-input-stats",
        summary="Reset E1.31 stats",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "channel__get-input-stats": Operation(
        id="channel__get-input-stats",
        method="GET",
        path="/api/channel/input/stats",
        tag="channel",
        cli_name="get-input-stats",
        summary="Get E1.31 stats",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "channel__get-output-processors": Operation(
        id="channel__get-output-processors",
        method="GET",
        path="/api/channel/output/processors",
        tag="channel",
        cli_name="get-output-processors",
        summary="Get output processors",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "channel__post-output-processors": Operation(
        id="channel__post-output-processors",
        method="POST",
        path="/api/channel/output/processors",
        tag="channel",
        cli_name="post-output-processors",
        summary="Set output processors",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "channel__get-output-file": Operation(
        id="channel__get-output-file",
        method="GET",
        path="/api/channel/output/{file}",
        tag="channel",
        cli_name="get-output-file",
        summary="Get channel output",
        path_params=('file',),
        query_params=(),
        mutating=False,
    ),
    "channel__post-output-file": Operation(
        id="channel__post-output-file",
        method="POST",
        path="/api/channel/output/{file}",
        tag="channel",
        cli_name="post-output-file",
        summary="Set channel output",
        path_params=('file',),
        query_params=(),
        mutating=True,
    ),
    "command__post-command": Operation(
        id="command__post-command",
        method="POST",
        path="/api/command",
        tag="command",
        cli_name="post-command",
        summary="command",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "command__get-command": Operation(
        id="command__get-command",
        method="GET",
        path="/api/command/{command}",
        tag="command",
        cli_name="get-command",
        summary="command/{command}",
        path_params=('command',),
        query_params=(),
        mutating=False,
    ),
    "command__post-command__1": Operation(
        id="command__post-command__1",
        method="POST",
        path="/api/command/{command}",
        tag="command",
        cli_name="post-command-1",
        summary="command/{command}",
        path_params=('command',),
        query_params=(),
        mutating=True,
    ),
    "commandPresets__get-commandpresets": Operation(
        id="commandPresets__get-commandpresets",
        method="GET",
        path="/api/commandPresets",
        tag="commandPresets",
        cli_name="get-commandpresets",
        summary="commandPresets",
        path_params=(),
        query_params=('names',),
        mutating=False,
    ),
    "commandPresets__get-name": Operation(
        id="commandPresets__get-name",
        method="GET",
        path="/api/commandPresets/{name}",
        tag="commandPresets",
        cli_name="get-name",
        summary="commandPresets/{name}",
        path_params=('name',),
        query_params=(),
        mutating=False,
    ),
    "commands__get-commands": Operation(
        id="commands__get-commands",
        method="GET",
        path="/api/commands",
        tag="commands",
        cli_name="get-commands",
        summary="commands",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "commands__get-command": Operation(
        id="commands__get-command",
        method="GET",
        path="/api/commands/{command}",
        tag="commands",
        cli_name="get-command",
        summary="commands/{command}",
        path_params=('command',),
        query_params=(),
        mutating=False,
    ),
    "configfile__get-configfile": Operation(
        id="configfile__get-configfile",
        method="GET",
        path="/api/configfile",
        tag="configfile",
        cli_name="get-configfile",
        summary="Get directory list",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "configfile__delete": Operation(
        id="configfile__delete",
        method="DELETE",
        path="/api/configfile/**",
        tag="configfile",
        cli_name="delete",
        summary="Delete configuration file",
        path_params=('_wildcard',),
        query_params=(),
        mutating=True,
    ),
    "configfile__get": Operation(
        id="configfile__get",
        method="GET",
        path="/api/configfile/**",
        tag="configfile",
        cli_name="get",
        summary="Get file or directory list",
        path_params=('_wildcard',),
        query_params=(),
        mutating=False,
    ),
    "configfile__post": Operation(
        id="configfile__post",
        method="POST",
        path="/api/configfile/**",
        tag="configfile",
        cli_name="post",
        summary="Upload configuration file",
        path_params=('_wildcard',),
        query_params=(),
        mutating=True,
    ),
    "dir__delete-dirname-subdir": Operation(
        id="dir__delete-dirname-subdir",
        method="DELETE",
        path="/api/dir/{DirName}/{SubDir}",
        tag="dir",
        cli_name="delete-dirname-subdir",
        summary="Delete empty subdirectory",
        path_params=('DirName', 'SubDir'),
        query_params=(),
        mutating=True,
    ),
    "dir__post-dirname-subdir": Operation(
        id="dir__post-dirname-subdir",
        method="POST",
        path="/api/dir/{DirName}/{SubDir}",
        tag="dir",
        cli_name="post-dirname-subdir",
        summary="Create subdirectory",
        path_params=('DirName', 'SubDir'),
        query_params=(),
        mutating=True,
    ),
    "effects__get-effects": Operation(
        id="effects__get-effects",
        method="GET",
        path="/api/effects",
        tag="effects",
        cli_name="get-effects",
        summary="Get effects",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "effects__get-all": Operation(
        id="effects__get-all",
        method="GET",
        path="/api/effects/ALL",
        tag="effects",
        cli_name="get-all",
        summary="Get all effects",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "email__post-configure": Operation(
        id="email__post-configure",
        method="POST",
        path="/api/email/configure",
        tag="email",
        cli_name="post-configure",
        summary="Set email options",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "email__post-test": Operation(
        id="email__post-test",
        method="POST",
        path="/api/email/test",
        tag="email",
        cli_name="post-test",
        summary="Send test email",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "events__get-events": Operation(
        id="events__get-events",
        method="GET",
        path="/api/events",
        tag="events",
        cli_name="get-events",
        summary="Get all event files",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "events__get-eventid": Operation(
        id="events__get-eventid",
        method="GET",
        path="/api/events/{eventId}",
        tag="events",
        cli_name="get-eventid",
        summary="Get event file",
        path_params=('eventId',),
        query_params=(),
        mutating=False,
    ),
    "events__get-eventid-trigger": Operation(
        id="events__get-eventid-trigger",
        method="GET",
        path="/api/events/{eventId}/trigger",
        tag="events",
        cli_name="get-eventid-trigger",
        summary="Trigger event",
        path_params=('eventId',),
        query_params=(),
        mutating=False,
    ),
    "file__get-info-plugin-ext-wildcard": Operation(
        id="file__get-info-plugin-ext-wildcard",
        method="GET",
        path="/api/file/info/{plugin}/{ext}/**",
        tag="file",
        cli_name="get-info-plugin-ext-wildcard",
        summary="Get plugin file info",
        path_params=('plugin', 'ext', '_wildcard'),
        query_params=(),
        mutating=False,
    ),
    "file__get-move-filename": Operation(
        id="file__get-move-filename",
        method="GET",
        path="/api/file/move/{fileName}",
        tag="file",
        cli_name="get-move-filename",
        summary="Move file",
        path_params=('fileName',),
        query_params=(),
        mutating=False,
    ),
    "file__get-onupload-ext-wildcard": Operation(
        id="file__get-onupload-ext-wildcard",
        method="GET",
        path="/api/file/onUpload/{ext}/**",
        tag="file",
        cli_name="get-onupload-ext-wildcard",
        summary="Notify plugin of upload",
        path_params=('ext', '_wildcard'),
        query_params=(),
        mutating=False,
    ),
    "file__post-dirname": Operation(
        id="file__post-dirname",
        method="POST",
        path="/api/file/{DirName}",
        tag="file",
        cli_name="post-dirname",
        summary="Upload file",
        path_params=('DirName',),
        query_params=(),
        mutating=True,
    ),
    "file__delete-dirname-wildcard": Operation(
        id="file__delete-dirname-wildcard",
        method="DELETE",
        path="/api/file/{DirName}/**",
        tag="file",
        cli_name="delete-dirname-wildcard",
        summary="Delete file or directory",
        path_params=('DirName', '_wildcard'),
        query_params=(),
        mutating=True,
    ),
    "file__get-dirname-wildcard": Operation(
        id="file__get-dirname-wildcard",
        method="GET",
        path="/api/file/{DirName}/**",
        tag="file",
        cli_name="get-dirname-wildcard",
        summary="Get file contents",
        path_params=('DirName', '_wildcard'),
        query_params=('tail', 'play', 'attach'),
        mutating=False,
    ),
    "file__post-dirname-copy-source-dest": Operation(
        id="file__post-dirname-copy-source-dest",
        method="POST",
        path="/api/file/{DirName}/copy/{source}/{dest}",
        tag="file",
        cli_name="post-dirname-copy-source-dest",
        summary="Copy file",
        path_params=('DirName', 'source', 'dest'),
        query_params=(),
        mutating=True,
    ),
    "file__post-dirname-rename-source-dest": Operation(
        id="file__post-dirname-rename-source-dest",
        method="POST",
        path="/api/file/{DirName}/rename/{source}/{dest}",
        tag="file",
        cli_name="post-dirname-rename-source-dest",
        summary="Rename file",
        path_params=('DirName', 'source', 'dest'),
        query_params=(),
        mutating=True,
    ),
    "file__get-dirname-tailfollow-tail": Operation(
        id="file__get-dirname-tailfollow-tail",
        method="GET",
        path="/api/file/{DirName}/tailfollow/*",
        tag="file",
        cli_name="get-dirname-tailfollow-tail",
        summary="Stream tail of file",
        path_params=('DirName', '_tail'),
        query_params=('lines',),
        mutating=False,
    ),
    "file__post-dirname-name": Operation(
        id="file__post-dirname-name",
        method="POST",
        path="/api/file/{DirName}/{Name}",
        tag="file",
        cli_name="post-dirname-name",
        summary="Upload file to directory",
        path_params=('DirName', 'Name'),
        query_params=('bs', 'sb'),
        mutating=True,
    ),
    "files__get-zip-dirnames": Operation(
        id="files__get-zip-dirnames",
        method="GET",
        path="/api/files/zip/{DirNames}",
        tag="files",
        cli_name="get-zip-dirnames",
        summary="Get zip file of directories",
        path_params=('DirNames',),
        query_params=(),
        mutating=False,
    ),
    "files__get-dirname": Operation(
        id="files__get-dirname",
        method="GET",
        path="/api/files/{DirName}",
        tag="files",
        cli_name="get-dirname",
        summary="Get all files",
        path_params=('DirName',),
        query_params=('nameOnly',),
        mutating=False,
    ),
    "fppd__delete-e131stats": Operation(
        id="fppd__delete-e131stats",
        method="DELETE",
        path="/api/fppd/e131stats",
        tag="fppd",
        cli_name="delete-e131stats",
        summary="fppd/e131stats",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-e131stats": Operation(
        id="fppd__get-e131stats",
        method="GET",
        path="/api/fppd/e131stats",
        tag="fppd",
        cli_name="get-e131stats",
        summary="fppd/e131stats",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-effects": Operation(
        id="fppd__get-effects",
        method="GET",
        path="/api/fppd/effects",
        tag="fppd",
        cli_name="get-effects",
        summary="fppd/effects",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__post-effects-name": Operation(
        id="fppd__post-effects-name",
        method="POST",
        path="/api/fppd/effects/{name}",
        tag="fppd",
        cli_name="post-effects-name",
        summary="fppd/effects/{name}",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-falcon-hardware": Operation(
        id="fppd__post-falcon-hardware",
        method="POST",
        path="/api/fppd/falcon/hardware",
        tag="fppd",
        cli_name="post-falcon-hardware",
        summary="fppd/falcon/hardware",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-gpio-ext": Operation(
        id="fppd__post-gpio-ext",
        method="POST",
        path="/api/fppd/gpio/ext",
        tag="fppd",
        cli_name="post-gpio-ext",
        summary="fppd/gpio/ext",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-log": Operation(
        id="fppd__get-log",
        method="GET",
        path="/api/fppd/log",
        tag="fppd",
        cli_name="get-log",
        summary="fppd/log",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__post-log-level-level": Operation(
        id="fppd__post-log-level-level",
        method="POST",
        path="/api/fppd/log/level/{level}",
        tag="fppd",
        cli_name="post-log-level-level",
        summary="fppd/log/level/{level}",
        path_params=('level',),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-mqtt-cache": Operation(
        id="fppd__get-mqtt-cache",
        method="GET",
        path="/api/fppd/mqtt/cache",
        tag="fppd",
        cli_name="get-mqtt-cache",
        summary="fppd/mqtt/cache",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-multisyncstats": Operation(
        id="fppd__get-multisyncstats",
        method="GET",
        path="/api/fppd/multiSyncStats",
        tag="fppd",
        cli_name="get-multisyncstats",
        summary="fppd/multiSyncStats",
        path_params=(),
        query_params=('reset',),
        mutating=False,
    ),
    "fppd__get-multisyncsystems": Operation(
        id="fppd__get-multisyncsystems",
        method="GET",
        path="/api/fppd/multiSyncSystems",
        tag="fppd",
        cli_name="get-multisyncsystems",
        summary="fppd/multiSyncSystems",
        path_params=(),
        query_params=('localOnly',),
        mutating=False,
    ),
    "fppd__post-outputs": Operation(
        id="fppd__post-outputs",
        method="POST",
        path="/api/fppd/outputs",
        tag="fppd",
        cli_name="post-outputs",
        summary="fppd/outputs",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-outputs-remap": Operation(
        id="fppd__post-outputs-remap",
        method="POST",
        path="/api/fppd/outputs/remap",
        tag="fppd",
        cli_name="post-outputs-remap",
        summary="fppd/outputs/remap",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-playlist-config": Operation(
        id="fppd__get-playlist-config",
        method="GET",
        path="/api/fppd/playlist/config",
        tag="fppd",
        cli_name="get-playlist-config",
        summary="fppd/playlist/config",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-playlist-filetime": Operation(
        id="fppd__get-playlist-filetime",
        method="GET",
        path="/api/fppd/playlist/filetime",
        tag="fppd",
        cli_name="get-playlist-filetime",
        summary="fppd/playlist/filetime",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-playlists": Operation(
        id="fppd__get-playlists",
        method="GET",
        path="/api/fppd/playlists",
        tag="fppd",
        cli_name="get-playlists",
        summary="fppd/playlists",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__post-playlists-stop": Operation(
        id="fppd__post-playlists-stop",
        method="POST",
        path="/api/fppd/playlists/stop",
        tag="fppd",
        cli_name="post-playlists-stop",
        summary="fppd/playlists/stop",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-playlists-name-item-item": Operation(
        id="fppd__post-playlists-name-item-item",
        method="POST",
        path="/api/fppd/playlists/{name}/item/{item}",
        tag="fppd",
        cli_name="post-playlists-name-item-item",
        summary="fppd/playlists/{name}/item/{item}",
        path_params=('name', 'item'),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-playlists-name-nextitem": Operation(
        id="fppd__post-playlists-name-nextitem",
        method="POST",
        path="/api/fppd/playlists/{name}/nextItem",
        tag="fppd",
        cli_name="post-playlists-name-nextitem",
        summary="fppd/playlists/{name}/nextItem",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-playlists-name-previtem": Operation(
        id="fppd__post-playlists-name-previtem",
        method="POST",
        path="/api/fppd/playlists/{name}/prevItem",
        tag="fppd",
        cli_name="post-playlists-name-previtem",
        summary="fppd/playlists/{name}/prevItem",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-playlists-name-restartitem": Operation(
        id="fppd__post-playlists-name-restartitem",
        method="POST",
        path="/api/fppd/playlists/{name}/restartItem",
        tag="fppd",
        cli_name="post-playlists-name-restartitem",
        summary="fppd/playlists/{name}/restartItem",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-playlists-name-section-section": Operation(
        id="fppd__post-playlists-name-section-section",
        method="POST",
        path="/api/fppd/playlists/{name}/section/{section}",
        tag="fppd",
        cli_name="post-playlists-name-section-section",
        summary="fppd/playlists/{name}/section/{section}",
        path_params=('name', 'section'),
        query_params=(),
        mutating=True,
    ),
    "fppd__put-playlists-name-settings": Operation(
        id="fppd__put-playlists-name-settings",
        method="PUT",
        path="/api/fppd/playlists/{name}/settings",
        tag="fppd",
        cli_name="put-playlists-name-settings",
        summary="fppd/playlists/{name}/settings",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-playlists-name-start": Operation(
        id="fppd__post-playlists-name-start",
        method="POST",
        path="/api/fppd/playlists/{name}/start",
        tag="fppd",
        cli_name="post-playlists-name-start",
        summary="fppd/playlists/{name}/start",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-playlists-name-stop": Operation(
        id="fppd__post-playlists-name-stop",
        method="POST",
        path="/api/fppd/playlists/{name}/stop",
        tag="fppd",
        cli_name="post-playlists-name-stop",
        summary="fppd/playlists/{name}/stop",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-ports": Operation(
        id="fppd__get-ports",
        method="GET",
        path="/api/fppd/ports",
        tag="fppd",
        cli_name="get-ports",
        summary="fppd/ports",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-ports-list": Operation(
        id="fppd__get-ports-list",
        method="GET",
        path="/api/fppd/ports/list",
        tag="fppd",
        cli_name="get-ports-list",
        summary="fppd/ports/list",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-ports-pixelcount": Operation(
        id="fppd__get-ports-pixelcount",
        method="GET",
        path="/api/fppd/ports/pixelCount",
        tag="fppd",
        cli_name="get-ports-pixelcount",
        summary="fppd/ports/pixelCount",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-ports-stop": Operation(
        id="fppd__get-ports-stop",
        method="GET",
        path="/api/fppd/ports/stop",
        tag="fppd",
        cli_name="get-ports-stop",
        summary="fppd/ports/stop",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__post-restart": Operation(
        id="fppd__post-restart",
        method="POST",
        path="/api/fppd/restart",
        tag="fppd",
        cli_name="post-restart",
        summary="fppd/restart",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-schedule": Operation(
        id="fppd__get-schedule",
        method="GET",
        path="/api/fppd/schedule",
        tag="fppd",
        cli_name="get-schedule",
        summary="fppd/schedule",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__post-schedule": Operation(
        id="fppd__post-schedule",
        method="POST",
        path="/api/fppd/schedule",
        tag="fppd",
        cli_name="post-schedule",
        summary="fppd/schedule",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-sequence": Operation(
        id="fppd__get-sequence",
        method="GET",
        path="/api/fppd/sequence",
        tag="fppd",
        cli_name="get-sequence",
        summary="fppd/sequence",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__post-sequences-name-back": Operation(
        id="fppd__post-sequences-name-back",
        method="POST",
        path="/api/fppd/sequences/{name}/back",
        tag="fppd",
        cli_name="post-sequences-name-back",
        summary="fppd/sequences/{name}/back",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-sequences-name-pause": Operation(
        id="fppd__post-sequences-name-pause",
        method="POST",
        path="/api/fppd/sequences/{name}/pause",
        tag="fppd",
        cli_name="post-sequences-name-pause",
        summary="fppd/sequences/{name}/pause",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-sequences-name-start": Operation(
        id="fppd__post-sequences-name-start",
        method="POST",
        path="/api/fppd/sequences/{name}/start",
        tag="fppd",
        cli_name="post-sequences-name-start",
        summary="fppd/sequences/{name}/start",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-sequences-name-step": Operation(
        id="fppd__post-sequences-name-step",
        method="POST",
        path="/api/fppd/sequences/{name}/step",
        tag="fppd",
        cli_name="post-sequences-name-step",
        summary="fppd/sequences/{name}/step",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-sequences-name-stop": Operation(
        id="fppd__post-sequences-name-stop",
        method="POST",
        path="/api/fppd/sequences/{name}/stop",
        tag="fppd",
        cli_name="post-sequences-name-stop",
        summary="fppd/sequences/{name}/stop",
        path_params=('name',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-settings-reload": Operation(
        id="fppd__post-settings-reload",
        method="POST",
        path="/api/fppd/settings/reload",
        tag="fppd",
        cli_name="post-settings-reload",
        summary="fppd/settings/reload",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-settings-reload-setting": Operation(
        id="fppd__post-settings-reload-setting",
        method="POST",
        path="/api/fppd/settings/reload/{setting}",
        tag="fppd",
        cli_name="post-settings-reload-setting",
        summary="fppd/settings/reload/{setting}",
        path_params=('setting',),
        query_params=(),
        mutating=True,
    ),
    "fppd__post-shutdown": Operation(
        id="fppd__post-shutdown",
        method="POST",
        path="/api/fppd/shutdown",
        tag="fppd",
        cli_name="post-shutdown",
        summary="fppd/shutdown",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-status": Operation(
        id="fppd__get-status",
        method="GET",
        path="/api/fppd/status",
        tag="fppd",
        cli_name="get-status",
        summary="fppd/status",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-testing": Operation(
        id="fppd__get-testing",
        method="GET",
        path="/api/fppd/testing",
        tag="fppd",
        cli_name="get-testing",
        summary="fppd/testing",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__post-testing": Operation(
        id="fppd__post-testing",
        method="POST",
        path="/api/fppd/testing",
        tag="fppd",
        cli_name="post-testing",
        summary="fppd/testing",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-testing-tests": Operation(
        id="fppd__get-testing-tests",
        method="GET",
        path="/api/fppd/testing/tests",
        tag="fppd",
        cli_name="get-testing-tests",
        summary="fppd/testing/tests",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-testing-tests-pattern": Operation(
        id="fppd__get-testing-tests-pattern",
        method="GET",
        path="/api/fppd/testing/tests/{pattern}",
        tag="fppd",
        cli_name="get-testing-tests-pattern",
        summary="fppd/testing/tests/{pattern}",
        path_params=('pattern',),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-version": Operation(
        id="fppd__get-version",
        method="GET",
        path="/api/fppd/version",
        tag="fppd",
        cli_name="get-version",
        summary="fppd/version",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-volume": Operation(
        id="fppd__get-volume",
        method="GET",
        path="/api/fppd/volume",
        tag="fppd",
        cli_name="get-volume",
        summary="fppd/volume",
        path_params=(),
        query_params=('set', 'simple'),
        mutating=False,
    ),
    "fppd__post-volume-volume": Operation(
        id="fppd__post-volume-volume",
        method="POST",
        path="/api/fppd/volume/{volume}",
        tag="fppd",
        cli_name="post-volume-volume",
        summary="fppd/volume/{volume}",
        path_params=('volume',),
        query_params=(),
        mutating=True,
    ),
    "fppd__get-warnings": Operation(
        id="fppd__get-warnings",
        method="GET",
        path="/api/fppd/warnings",
        tag="fppd",
        cli_name="get-warnings",
        summary="fppd/warnings",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "fppd__get-warnings-full": Operation(
        id="fppd__get-warnings-full",
        method="GET",
        path="/api/fppd/warnings_full",
        tag="fppd",
        cli_name="get-warnings-full",
        summary="fppd/warnings_full",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "git__get-branches": Operation(
        id="git__get-branches",
        method="GET",
        path="/api/git/branches",
        tag="git",
        cli_name="get-branches",
        summary="Get local branches",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "git__get-originlog": Operation(
        id="git__get-originlog",
        method="GET",
        path="/api/git/originLog",
        tag="git",
        cli_name="get-originlog",
        summary="Get origin commits",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "git__get-releases-os-all": Operation(
        id="git__get-releases-os-all",
        method="GET",
        path="/api/git/releases/os/{All}",
        tag="git",
        cli_name="get-releases-os-all",
        summary="Get releases for OS",
        path_params=('All',),
        query_params=(),
        mutating=False,
    ),
    "git__get-releases-sizes": Operation(
        id="git__get-releases-sizes",
        method="GET",
        path="/api/git/releases/sizes",
        tag="git",
        cli_name="get-releases-sizes",
        summary="Get release asset sizes",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "git__get-reset": Operation(
        id="git__get-reset",
        method="GET",
        path="/api/git/reset",
        tag="git",
        cli_name="get-reset",
        summary="git/reset",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "git__get-status": Operation(
        id="git__get-status",
        method="GET",
        path="/api/git/status",
        tag="git",
        cli_name="get-status",
        summary="Get local repo status",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "gpio__get-gpio": Operation(
        id="gpio__get-gpio",
        method="GET",
        path="/api/gpio",
        tag="gpio",
        cli_name="get-gpio",
        summary="gpio",
        path_params=(),
        query_params=('list',),
        mutating=False,
    ),
    "gpio__get-pin": Operation(
        id="gpio__get-pin",
        method="GET",
        path="/api/gpio/{pin}",
        tag="gpio",
        cli_name="get-pin",
        summary="gpio/{pin}",
        path_params=('pin',),
        query_params=(),
        mutating=False,
    ),
    "gpio__post-pin": Operation(
        id="gpio__post-pin",
        method="POST",
        path="/api/gpio/{pin}",
        tag="gpio",
        cli_name="post-pin",
        summary="gpio/{pin}",
        path_params=('pin',),
        query_params=(),
        mutating=True,
    ),
    "help__get-help": Operation(
        id="help__get-help",
        method="GET",
        path="/api/help",
        tag="help",
        cli_name="get-help",
        summary="help",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "media__get-media": Operation(
        id="media__get-media",
        method="GET",
        path="/api/media",
        tag="media",
        cli_name="get-media",
        summary="List all media files",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "media__get-medianame-duration": Operation(
        id="media__get-medianame-duration",
        method="GET",
        path="/api/media/{MediaName}/duration",
        tag="media",
        cli_name="get-medianame-duration",
        summary="Get duration of media item",
        path_params=('MediaName',),
        query_params=(),
        mutating=False,
    ),
    "media__get-medianame-meta": Operation(
        id="media__get-medianame-meta",
        method="GET",
        path="/api/media/{MediaName}/meta",
        tag="media",
        cli_name="get-medianame-meta",
        summary="Get metadata for media item",
        path_params=('MediaName',),
        query_params=(),
        mutating=False,
    ),
    "models__get-models": Operation(
        id="models__get-models",
        method="GET",
        path="/api/models",
        tag="models",
        cli_name="get-models",
        summary="models",
        path_params=(),
        query_params=('simple', 'all'),
        mutating=False,
    ),
    "models__post-models": Operation(
        id="models__post-models",
        method="POST",
        path="/api/models",
        tag="models",
        cli_name="post-models",
        summary="models",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "models__post-raw": Operation(
        id="models__post-raw",
        method="POST",
        path="/api/models/raw",
        tag="models",
        cli_name="post-raw",
        summary="models/raw",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "models__get-model": Operation(
        id="models__get-model",
        method="GET",
        path="/api/models/{model}",
        tag="models",
        cli_name="get-model",
        summary="models/{model}",
        path_params=('model',),
        query_params=(),
        mutating=False,
    ),
    "network__get-dns": Operation(
        id="network__get-dns",
        method="GET",
        path="/api/network/dns",
        tag="network",
        cli_name="get-dns",
        summary="Get DNS configuration",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "network__post-dns": Operation(
        id="network__post-dns",
        method="POST",
        path="/api/network/dns",
        tag="network",
        cli_name="post-dns",
        summary="Set DNS configuration",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "network__get-gateway": Operation(
        id="network__get-gateway",
        method="GET",
        path="/api/network/gateway",
        tag="network",
        cli_name="get-gateway",
        summary="Get default gateway",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "network__post-gateway": Operation(
        id="network__post-gateway",
        method="POST",
        path="/api/network/gateway",
        tag="network",
        cli_name="post-gateway",
        summary="Set default gateway",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "network__get-interface": Operation(
        id="network__get-interface",
        method="GET",
        path="/api/network/interface",
        tag="network",
        cli_name="get-interface",
        summary="Get network interface details",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "network__get-interface-add-interface": Operation(
        id="network__get-interface-add-interface",
        method="GET",
        path="/api/network/interface/add/{interface}",
        tag="network",
        cli_name="get-interface-add-interface",
        summary="Create DHCP interface",
        path_params=('interface',),
        query_params=(),
        mutating=False,
    ),
    "network__get-interface-interface": Operation(
        id="network__get-interface-interface",
        method="GET",
        path="/api/network/interface/{interface}",
        tag="network",
        cli_name="get-interface-interface",
        summary="Get network interface configuration",
        path_params=('interface',),
        query_params=(),
        mutating=False,
    ),
    "network__post-interface-interface": Operation(
        id="network__post-interface-interface",
        method="POST",
        path="/api/network/interface/{interface}",
        tag="network",
        cli_name="post-interface-interface",
        summary="Set network interface configuration",
        path_params=('interface',),
        query_params=(),
        mutating=True,
    ),
    "network__post-interface-interface-apply": Operation(
        id="network__post-interface-interface-apply",
        method="POST",
        path="/api/network/interface/{interface}/apply",
        tag="network",
        cli_name="post-interface-interface-apply",
        summary="Set networking configuration",
        path_params=('interface',),
        query_params=(),
        mutating=True,
    ),
    "network__delete-persistentnames": Operation(
        id="network__delete-persistentnames",
        method="DELETE",
        path="/api/network/persistentNames",
        tag="network",
        cli_name="delete-persistentnames",
        summary="Delete interface persistent names",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "network__post-persistentnames": Operation(
        id="network__post-persistentnames",
        method="POST",
        path="/api/network/persistentNames",
        tag="network",
        cli_name="post-persistentnames",
        summary="Set interface persistent names",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "network__get-wifi-scan-interface": Operation(
        id="network__get-wifi-scan-interface",
        method="GET",
        path="/api/network/wifi/scan/{interface}",
        tag="network",
        cli_name="get-wifi-scan-interface",
        summary="Get discoverable wifi networks",
        path_params=('interface',),
        query_params=(),
        mutating=False,
    ),
    "network__get-wifi-strength": Operation(
        id="network__get-wifi-strength",
        method="GET",
        path="/api/network/wifi/strength",
        tag="network",
        cli_name="get-wifi-strength",
        summary="Get all wifi signal strenths",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "options__get-settingname": Operation(
        id="options__get-settingname",
        method="GET",
        path="/api/options/{SettingName}",
        tag="options",
        cli_name="get-settingname",
        summary="Get a setting's options",
        path_params=('SettingName',),
        query_params=(),
        mutating=False,
    ),
    "overlays__get-effects": Operation(
        id="overlays__get-effects",
        method="GET",
        path="/api/overlays/effects",
        tag="overlays",
        cli_name="get-effects",
        summary="overlays/effects",
        path_params=(),
        query_params=('full',),
        mutating=False,
    ),
    "overlays__get-effects-effect": Operation(
        id="overlays__get-effects-effect",
        method="GET",
        path="/api/overlays/effects/{effect}",
        tag="overlays",
        cli_name="get-effects-effect",
        summary="overlays/effects/{effect}",
        path_params=('effect',),
        query_params=(),
        mutating=False,
    ),
    "overlays__get-fonts": Operation(
        id="overlays__get-fonts",
        method="GET",
        path="/api/overlays/fonts",
        tag="overlays",
        cli_name="get-fonts",
        summary="overlays/fonts",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "overlays__get-model-model": Operation(
        id="overlays__get-model-model",
        method="GET",
        path="/api/overlays/model/{model}",
        tag="overlays",
        cli_name="get-model-model",
        summary="overlays/model/{model}",
        path_params=('model',),
        query_params=(),
        mutating=False,
    ),
    "overlays__get-model-model-clear": Operation(
        id="overlays__get-model-model-clear",
        method="GET",
        path="/api/overlays/model/{model}/clear",
        tag="overlays",
        cli_name="get-model-model-clear",
        summary="overlays/model/{model}/clear",
        path_params=('model',),
        query_params=(),
        mutating=False,
    ),
    "overlays__get-model-model-data": Operation(
        id="overlays__get-model-model-data",
        method="GET",
        path="/api/overlays/model/{model}/data",
        tag="overlays",
        cli_name="get-model-model-data",
        summary="overlays/model/{model}/data",
        path_params=('model',),
        query_params=(),
        mutating=False,
    ),
    "overlays__put-model-model-fill": Operation(
        id="overlays__put-model-model-fill",
        method="PUT",
        path="/api/overlays/model/{model}/fill",
        tag="overlays",
        cli_name="put-model-model-fill",
        summary="overlays/model/{model}/fill",
        path_params=('model',),
        query_params=(),
        mutating=True,
    ),
    "overlays__put-model-model-mmap": Operation(
        id="overlays__put-model-model-mmap",
        method="PUT",
        path="/api/overlays/model/{model}/mmap",
        tag="overlays",
        cli_name="put-model-model-mmap",
        summary="overlays/model/{model}/mmap",
        path_params=('model',),
        query_params=(),
        mutating=True,
    ),
    "overlays__put-model-model-pixel": Operation(
        id="overlays__put-model-model-pixel",
        method="PUT",
        path="/api/overlays/model/{model}/pixel",
        tag="overlays",
        cli_name="put-model-model-pixel",
        summary="overlays/model/{model}/pixel",
        path_params=('model',),
        query_params=(),
        mutating=True,
    ),
    "overlays__put-model-model-save": Operation(
        id="overlays__put-model-model-save",
        method="PUT",
        path="/api/overlays/model/{model}/save",
        tag="overlays",
        cli_name="put-model-model-save",
        summary="overlays/model/{model}/save",
        path_params=('model',),
        query_params=(),
        mutating=True,
    ),
    "overlays__put-model-model-state": Operation(
        id="overlays__put-model-model-state",
        method="PUT",
        path="/api/overlays/model/{model}/state",
        tag="overlays",
        cli_name="put-model-model-state",
        summary="overlays/model/{model}/state",
        path_params=('model',),
        query_params=(),
        mutating=True,
    ),
    "overlays__put-model-model-text": Operation(
        id="overlays__put-model-model-text",
        method="PUT",
        path="/api/overlays/model/{model}/text",
        tag="overlays",
        cli_name="put-model-model-text",
        summary="overlays/model/{model}/text",
        path_params=('model',),
        query_params=(),
        mutating=True,
    ),
    "overlays__get-models": Operation(
        id="overlays__get-models",
        method="GET",
        path="/api/overlays/models",
        tag="overlays",
        cli_name="get-models",
        summary="overlays/models",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "overlays__put-range-ranges": Operation(
        id="overlays__put-range-ranges",
        method="PUT",
        path="/api/overlays/range/{ranges}",
        tag="overlays",
        cli_name="put-range-ranges",
        summary="overlays/range/{ranges}",
        path_params=('ranges',),
        query_params=(),
        mutating=True,
    ),
    "overlays__get-running": Operation(
        id="overlays__get-running",
        method="GET",
        path="/api/overlays/running",
        tag="overlays",
        cli_name="get-running",
        summary="overlays/running",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "overlays__get-settings": Operation(
        id="overlays__get-settings",
        method="GET",
        path="/api/overlays/settings",
        tag="overlays",
        cli_name="get-settings",
        summary="overlays/settings",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "pipewire__get-control-groups": Operation(
        id="pipewire__get-control-groups",
        method="GET",
        path="/api/pipewire/control/groups",
        tag="pipewire",
        cli_name="get-control-groups",
        summary="List output groups with live state",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "pipewire__get-control-groups-id": Operation(
        id="pipewire__get-control-groups-id",
        method="GET",
        path="/api/pipewire/control/groups/{id}",
        tag="pipewire",
        cli_name="get-control-groups-id",
        summary="Get one output group with live state",
        path_params=('id',),
        query_params=(),
        mutating=False,
    ),
    "pipewire__post-control-groups-id-members-cardid-mute": Operation(
        id="pipewire__post-control-groups-id-members-cardid-mute",
        method="POST",
        path="/api/pipewire/control/groups/{id}/members/{cardId}/mute",
        tag="pipewire",
        cli_name="post-control-groups-id-members-cardid-mute",
        summary="Mute or unmute a member sound card",
        path_params=('id', 'cardId'),
        query_params=(),
        mutating=True,
    ),
    "pipewire__post-control-groups-id-members-cardid-volume": Operation(
        id="pipewire__post-control-groups-id-members-cardid-volume",
        method="POST",
        path="/api/pipewire/control/groups/{id}/members/{cardId}/volume",
        tag="pipewire",
        cli_name="post-control-groups-id-members-cardid-volume",
        summary="Set member sound-card volume",
        path_params=('id', 'cardId'),
        query_params=(),
        mutating=True,
    ),
    "pipewire__post-control-groups-id-mute": Operation(
        id="pipewire__post-control-groups-id-mute",
        method="POST",
        path="/api/pipewire/control/groups/{id}/mute",
        tag="pipewire",
        cli_name="post-control-groups-id-mute",
        summary="Mute or unmute an output group",
        path_params=('id',),
        query_params=(),
        mutating=True,
    ),
    "pipewire__post-control-groups-id-volume": Operation(
        id="pipewire__post-control-groups-id-volume",
        method="POST",
        path="/api/pipewire/control/groups/{id}/volume",
        tag="pipewire",
        cli_name="post-control-groups-id-volume",
        summary="Set output group volume",
        path_params=('id',),
        query_params=(),
        mutating=True,
    ),
    "pipewire__get-control-input-groups": Operation(
        id="pipewire__get-control-input-groups",
        method="GET",
        path="/api/pipewire/control/input-groups",
        tag="pipewire",
        cli_name="get-control-input-groups",
        summary="List input groups (mix buses)",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "pipewire__get-control-input-groups-id": Operation(
        id="pipewire__get-control-input-groups-id",
        method="GET",
        path="/api/pipewire/control/input-groups/{id}",
        tag="pipewire",
        cli_name="get-control-input-groups-id",
        summary="Get one input group (mix bus)",
        path_params=('id',),
        query_params=(),
        mutating=False,
    ),
    "pipewire__post-control-input-groups-id-members-memberindex-mute": Operation(
        id="pipewire__post-control-input-groups-id-members-memberindex-mute",
        method="POST",
        path="/api/pipewire/control/input-groups/{id}/members/{memberIndex}/mute",
        tag="pipewire",
        cli_name="post-control-input-groups-id-members-memberindex-mute",
        summary="Mute or unmute an input-group member",
        path_params=('id', 'memberIndex'),
        query_params=(),
        mutating=True,
    ),
    "pipewire__post-control-input-groups-id-members-memberindex-volume": Operation(
        id="pipewire__post-control-input-groups-id-members-memberindex-volume",
        method="POST",
        path="/api/pipewire/control/input-groups/{id}/members/{memberIndex}/volume",
        tag="pipewire",
        cli_name="post-control-input-groups-id-members-memberindex-volume",
        summary="Set input-group member volume",
        path_params=('id', 'memberIndex'),
        query_params=(),
        mutating=True,
    ),
    "pipewire__get-control-routing": Operation(
        id="pipewire__get-control-routing",
        method="GET",
        path="/api/pipewire/control/routing",
        tag="pipewire",
        cli_name="get-control-routing",
        summary="Get the routing matrix",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "pipewire__post-control-routing-inputgroupid-outputgroupid-mute": Operation(
        id="pipewire__post-control-routing-inputgroupid-outputgroupid-mute",
        method="POST",
        path="/api/pipewire/control/routing/{inputGroupId}/{outputGroupId}/mute",
        tag="pipewire",
        cli_name="post-control-routing-inputgroupid-outputgroupid-mute",
        summary="Mute or unmute a routing path",
        path_params=('inputGroupId', 'outputGroupId'),
        query_params=(),
        mutating=True,
    ),
    "pipewire__post-control-routing-inputgroupid-outputgroupid-volume": Operation(
        id="pipewire__post-control-routing-inputgroupid-outputgroupid-volume",
        method="POST",
        path="/api/pipewire/control/routing/{inputGroupId}/{outputGroupId}/volume",
        tag="pipewire",
        cli_name="post-control-routing-inputgroupid-outputgroupid-volume",
        summary="Set routing-path volume",
        path_params=('inputGroupId', 'outputGroupId'),
        query_params=(),
        mutating=True,
    ),
    "pipewire__get-control-status": Operation(
        id="pipewire__get-control-status",
        method="GET",
        path="/api/pipewire/control/status",
        tag="pipewire",
        cli_name="get-control-status",
        summary="PipeWire control status",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "pipewire__get-control-streams": Operation(
        id="pipewire__get-control-streams",
        method="GET",
        path="/api/pipewire/control/streams",
        tag="pipewire",
        cli_name="get-control-streams",
        summary="List fppd stream slots",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "pipewire__post-control-streams-slot-volume": Operation(
        id="pipewire__post-control-streams-slot-volume",
        method="POST",
        path="/api/pipewire/control/streams/{slot}/volume",
        tag="pipewire",
        cli_name="post-control-streams-slot-volume",
        summary="Set fppd stream slot volume",
        path_params=('slot',),
        query_params=(),
        mutating=True,
    ),
    "player__get-player": Operation(
        id="player__get-player",
        method="GET",
        path="/api/player",
        tag="player",
        cli_name="get-player",
        summary="player",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "player__get-current": Operation(
        id="player__get-current",
        method="GET",
        path="/api/player/current",
        tag="player",
        cli_name="get-current",
        summary="player/current",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "player__get-status": Operation(
        id="player__get-status",
        method="GET",
        path="/api/player/status",
        tag="player",
        cli_name="get-status",
        summary="player/status",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlist__delete-playlistname": Operation(
        id="playlist__delete-playlistname",
        method="DELETE",
        path="/api/playlist/{PlaylistName}",
        tag="playlist",
        cli_name="delete-playlistname",
        summary="Delete playlist",
        path_params=('PlaylistName',),
        query_params=(),
        mutating=True,
    ),
    "playlist__get-playlistname": Operation(
        id="playlist__get-playlistname",
        method="GET",
        path="/api/playlist/{PlaylistName}",
        tag="playlist",
        cli_name="get-playlistname",
        summary="Get a playlist",
        path_params=('PlaylistName',),
        query_params=('mergeSubs',),
        mutating=False,
    ),
    "playlist__post-playlistname": Operation(
        id="playlist__post-playlistname",
        method="POST",
        path="/api/playlist/{PlaylistName}",
        tag="playlist",
        cli_name="post-playlistname",
        summary="Upsert playlist",
        path_params=('PlaylistName',),
        query_params=(),
        mutating=True,
    ),
    "playlist__get-playlistname-start": Operation(
        id="playlist__get-playlistname-start",
        method="GET",
        path="/api/playlist/{PlaylistName}/start",
        tag="playlist",
        cli_name="get-playlistname-start",
        summary="Start playlist",
        path_params=('PlaylistName',),
        query_params=(),
        mutating=False,
    ),
    "playlist__get-playlistname-start-repeat": Operation(
        id="playlist__get-playlistname-start-repeat",
        method="GET",
        path="/api/playlist/{PlaylistName}/start/{Repeat}",
        tag="playlist",
        cli_name="get-playlistname-start-repeat",
        summary="Start playlist on repeat",
        path_params=('PlaylistName', 'Repeat'),
        query_params=('scheduleProtected',),
        mutating=False,
    ),
    "playlist__get-playlistname-start-repeat-scheduleprotected": Operation(
        id="playlist__get-playlistname-start-repeat-scheduleprotected",
        method="GET",
        path="/api/playlist/{PlaylistName}/start/{Repeat}/{ScheduleProtected}",
        tag="playlist",
        cli_name="get-playlistname-start-repeat-scheduleprotected",
        summary="Start playlist on repeat (alt)",
        path_params=('PlaylistName', 'Repeat', 'ScheduleProtected'),
        query_params=(),
        mutating=False,
    ),
    "playlist__post-playlistname-sectionname-item": Operation(
        id="playlist__post-playlistname-sectionname-item",
        method="POST",
        path="/api/playlist/{PlaylistName}/{SectionName}/item",
        tag="playlist",
        cli_name="post-playlistname-sectionname-item",
        summary="Insert section into playlist",
        path_params=('PlaylistName', 'SectionName'),
        query_params=(),
        mutating=True,
    ),
    "playlists__get-playlists": Operation(
        id="playlists__get-playlists",
        method="GET",
        path="/api/playlists",
        tag="playlists",
        cli_name="get-playlists",
        summary="Get all playlists",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlists__post-playlists": Operation(
        id="playlists__post-playlists",
        method="POST",
        path="/api/playlists",
        tag="playlists",
        cli_name="post-playlists",
        summary="Create playlist",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "playlists__get-pause": Operation(
        id="playlists__get-pause",
        method="GET",
        path="/api/playlists/pause",
        tag="playlists",
        cli_name="get-pause",
        summary="Pause currently running playlist",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlists__get-playable": Operation(
        id="playlists__get-playable",
        method="GET",
        path="/api/playlists/playable",
        tag="playlists",
        cli_name="get-playable",
        summary="Get playable objects",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlists__get-resume": Operation(
        id="playlists__get-resume",
        method="GET",
        path="/api/playlists/resume",
        tag="playlists",
        cli_name="get-resume",
        summary="Resume paused playlist",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlists__get-stop": Operation(
        id="playlists__get-stop",
        method="GET",
        path="/api/playlists/stop",
        tag="playlists",
        cli_name="get-stop",
        summary="Stop playlist",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlists__get-stopgracefully": Operation(
        id="playlists__get-stopgracefully",
        method="GET",
        path="/api/playlists/stopgracefully",
        tag="playlists",
        cli_name="get-stopgracefully",
        summary="Gracefully stop playlist",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlists__get-stopgracefullyafterloop": Operation(
        id="playlists__get-stopgracefullyafterloop",
        method="GET",
        path="/api/playlists/stopgracefullyafterloop",
        tag="playlists",
        cli_name="get-stopgracefullyafterloop",
        summary="Gracefully stop at end of loop",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "playlists__get-validate": Operation(
        id="playlists__get-validate",
        method="GET",
        path="/api/playlists/validate",
        tag="playlists",
        cli_name="get-validate",
        summary="Validate all playlists",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "plugin__get-plugin": Operation(
        id="plugin__get-plugin",
        method="GET",
        path="/api/plugin",
        tag="plugin",
        cli_name="get-plugin",
        summary="Get all plugins",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "plugin__post-plugin": Operation(
        id="plugin__post-plugin",
        method="POST",
        path="/api/plugin",
        tag="plugin",
        cli_name="post-plugin",
        summary="Install plugin",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "plugin__post-fetchinfo": Operation(
        id="plugin__post-fetchinfo",
        method="POST",
        path="/api/plugin/fetchInfo",
        tag="plugin",
        cli_name="post-fetchinfo",
        summary="Get plugin info from URL",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "plugin__get-headerindicators": Operation(
        id="plugin__get-headerindicators",
        method="GET",
        path="/api/plugin/headerIndicators",
        tag="plugin",
        cli_name="get-headerindicators",
        summary="Get header indicators",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "plugin__delete-reponame": Operation(
        id="plugin__delete-reponame",
        method="DELETE",
        path="/api/plugin/{RepoName}",
        tag="plugin",
        cli_name="delete-reponame",
        summary="Uninstall plugin",
        path_params=('RepoName',),
        query_params=(),
        mutating=True,
    ),
    "plugin__get-reponame": Operation(
        id="plugin__get-reponame",
        method="GET",
        path="/api/plugin/{RepoName}",
        tag="plugin",
        cli_name="get-reponame",
        summary="Get plugin information",
        path_params=('RepoName',),
        query_params=(),
        mutating=False,
    ),
    "plugin__get-reponame-settings-settingname": Operation(
        id="plugin__get-reponame-settings-settingname",
        method="GET",
        path="/api/plugin/{RepoName}/settings/{SettingName}",
        tag="plugin",
        cli_name="get-reponame-settings-settingname",
        summary="Get setting from plugin",
        path_params=('RepoName', 'SettingName'),
        query_params=(),
        mutating=False,
    ),
    "plugin__post-reponame-settings-settingname": Operation(
        id="plugin__post-reponame-settings-settingname",
        method="POST",
        path="/api/plugin/{RepoName}/settings/{SettingName}",
        tag="plugin",
        cli_name="post-reponame-settings-settingname",
        summary="Set setting for plugin",
        path_params=('RepoName', 'SettingName'),
        query_params=(),
        mutating=True,
    ),
    "plugin__post-reponame-updates": Operation(
        id="plugin__post-reponame-updates",
        method="POST",
        path="/api/plugin/{RepoName}/updates",
        tag="plugin",
        cli_name="post-reponame-updates",
        summary="Check plugin for updates",
        path_params=('RepoName',),
        query_params=(),
        mutating=True,
    ),
    "plugin__get-reponame-upgrade": Operation(
        id="plugin__get-reponame-upgrade",
        method="GET",
        path="/api/plugin/{RepoName}/upgrade",
        tag="plugin",
        cli_name="get-reponame-upgrade",
        summary="Update plugin",
        path_params=('RepoName',),
        query_params=(),
        mutating=False,
    ),
    "proxies__delete-proxies": Operation(
        id="proxies__delete-proxies",
        method="DELETE",
        path="/api/proxies",
        tag="proxies",
        cli_name="delete-proxies",
        summary="Delete all proxies",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "proxies__get-proxies": Operation(
        id="proxies__get-proxies",
        method="GET",
        path="/api/proxies",
        tag="proxies",
        cli_name="get-proxies",
        summary="Get list of proxy IPs",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "proxies__post-proxies": Operation(
        id="proxies__post-proxies",
        method="POST",
        path="/api/proxies",
        tag="proxies",
        cli_name="post-proxies",
        summary="Set proxy list",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "proxies__delete-proxyip": Operation(
        id="proxies__delete-proxyip",
        method="DELETE",
        path="/api/proxies/{ProxyIp}",
        tag="proxies",
        cli_name="delete-proxyip",
        summary="Remove proxy",
        path_params=('ProxyIp',),
        query_params=(),
        mutating=True,
    ),
    "proxies__post-proxyip": Operation(
        id="proxies__post-proxyip",
        method="POST",
        path="/api/proxies/{ProxyIp}",
        tag="proxies",
        cli_name="post-proxyip",
        summary="Add proxy",
        path_params=('ProxyIp',),
        query_params=(),
        mutating=True,
    ),
    "proxy__get-ip-urlpart": Operation(
        id="proxy__get-ip-urlpart",
        method="GET",
        path="/api/proxy/{Ip}/{urlPart}",
        tag="proxy",
        cli_name="get-ip-urlpart",
        summary="Get URL from remote FPP",
        path_params=('Ip', 'urlPart'),
        query_params=(),
        mutating=False,
    ),
    "remoteAction__get-remoteaction": Operation(
        id="remoteAction__get-remoteaction",
        method="GET",
        path="/api/remoteAction",
        tag="remoteAction",
        cli_name="get-remoteaction",
        summary="Proxy a command to remote FPP",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "remotes__get-remotes": Operation(
        id="remotes__get-remotes",
        method="GET",
        path="/api/remotes",
        tag="remotes",
        cli_name="get-remotes",
        summary="Get all remote FPPs",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "schedule__get-schedule": Operation(
        id="schedule__get-schedule",
        method="GET",
        path="/api/schedule",
        tag="schedule",
        cli_name="get-schedule",
        summary="Get schedules",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "schedule__post-schedule": Operation(
        id="schedule__post-schedule",
        method="POST",
        path="/api/schedule",
        tag="schedule",
        cli_name="post-schedule",
        summary="Set schedule",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "schedule__post-reload": Operation(
        id="schedule__post-reload",
        method="POST",
        path="/api/schedule/reload",
        tag="schedule",
        cli_name="post-reload",
        summary="Reload schedules",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "scripts__get-scripts": Operation(
        id="scripts__get-scripts",
        method="GET",
        path="/api/scripts",
        tag="scripts",
        cli_name="get-scripts",
        summary="Get all scripts",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "scripts__get-installremote-category-filename": Operation(
        id="scripts__get-installremote-category-filename",
        method="GET",
        path="/api/scripts/installRemote/{category}/{filename}",
        tag="scripts",
        cli_name="get-installremote-category-filename",
        summary="Install remote script",
        path_params=('category', 'filename'),
        query_params=(),
        mutating=False,
    ),
    "scripts__get-viewremote-category-filename": Operation(
        id="scripts__get-viewremote-category-filename",
        method="GET",
        path="/api/scripts/viewRemote/{category}/{filename}",
        tag="scripts",
        cli_name="get-viewremote-category-filename",
        summary="Get remote script",
        path_params=('category', 'filename'),
        query_params=(),
        mutating=False,
    ),
    "scripts__get-scriptname": Operation(
        id="scripts__get-scriptname",
        method="GET",
        path="/api/scripts/{scriptName}",
        tag="scripts",
        cli_name="get-scriptname",
        summary="Get a script",
        path_params=('scriptName',),
        query_params=(),
        mutating=False,
    ),
    "scripts__post-scriptname": Operation(
        id="scripts__post-scriptname",
        method="POST",
        path="/api/scripts/{scriptName}",
        tag="scripts",
        cli_name="post-scriptname",
        summary="Update script",
        path_params=('scriptName',),
        query_params=(),
        mutating=True,
    ),
    "scripts__get-scriptname-run": Operation(
        id="scripts__get-scriptname-run",
        method="GET",
        path="/api/scripts/{scriptName}/run",
        tag="scripts",
        cli_name="get-scriptname-run",
        summary="Run script",
        path_params=('scriptName',),
        query_params=(),
        mutating=False,
    ),
    "sequence__get-sequence": Operation(
        id="sequence__get-sequence",
        method="GET",
        path="/api/sequence",
        tag="sequence",
        cli_name="get-sequence",
        summary="Get all sequences",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "sequence__get-current-step": Operation(
        id="sequence__get-current-step",
        method="GET",
        path="/api/sequence/current/step",
        tag="sequence",
        cli_name="get-current-step",
        summary="Step a paused sequence",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "sequence__get-current-stop": Operation(
        id="sequence__get-current-stop",
        method="GET",
        path="/api/sequence/current/stop",
        tag="sequence",
        cli_name="get-current-stop",
        summary="Stop sequence",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "sequence__get-current-togglepause": Operation(
        id="sequence__get-current-togglepause",
        method="GET",
        path="/api/sequence/current/togglePause",
        tag="sequence",
        cli_name="get-current-togglepause",
        summary="Toggle play/pause on sequence",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "sequence__delete-sequencename": Operation(
        id="sequence__delete-sequencename",
        method="DELETE",
        path="/api/sequence/{SequenceName}",
        tag="sequence",
        cli_name="delete-sequencename",
        summary="Delete sequence file",
        path_params=('SequenceName',),
        query_params=(),
        mutating=True,
    ),
    "sequence__get-sequencename": Operation(
        id="sequence__get-sequencename",
        method="GET",
        path="/api/sequence/{SequenceName}",
        tag="sequence",
        cli_name="get-sequencename",
        summary="Download sequence",
        path_params=('SequenceName',),
        query_params=(),
        mutating=False,
    ),
    "sequence__post-sequencename": Operation(
        id="sequence__post-sequencename",
        method="POST",
        path="/api/sequence/{SequenceName}",
        tag="sequence",
        cli_name="post-sequencename",
        summary="Uploads sequence file",
        path_params=('SequenceName',),
        query_params=(),
        mutating=True,
    ),
    "sequence__get-sequencename-meta": Operation(
        id="sequence__get-sequencename-meta",
        method="GET",
        path="/api/sequence/{SequenceName}/meta",
        tag="sequence",
        cli_name="get-sequencename-meta",
        summary="Get sequence metadata",
        path_params=('SequenceName',),
        query_params=(),
        mutating=False,
    ),
    "sequence__get-sequencename-start-startsecond": Operation(
        id="sequence__get-sequencename-start-startsecond",
        method="GET",
        path="/api/sequence/{SequenceName}/start/{startSecond}",
        tag="sequence",
        cli_name="get-sequencename-start-startsecond",
        summary="Start sequence at time",
        path_params=('SequenceName', 'startSecond'),
        query_params=(),
        mutating=False,
    ),
    "settings__get-settings": Operation(
        id="settings__get-settings",
        method="GET",
        path="/api/settings",
        tag="settings",
        cli_name="get-settings",
        summary="Get all settings.json",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "settings__get-settingname": Operation(
        id="settings__get-settingname",
        method="GET",
        path="/api/settings/{SettingName}",
        tag="settings",
        cli_name="get-settingname",
        summary="Get value of setting",
        path_params=('SettingName',),
        query_params=(),
        mutating=False,
    ),
    "settings__put-settingname": Operation(
        id="settings__put-settingname",
        method="PUT",
        path="/api/settings/{SettingName}",
        tag="settings",
        cli_name="put-settingname",
        summary="Set value for setting",
        path_params=('SettingName',),
        query_params=(),
        mutating=True,
    ),
    "settings__put-settingname-jsonvalueupdate": Operation(
        id="settings__put-settingname-jsonvalueupdate",
        method="PUT",
        path="/api/settings/{SettingName}/jsonValueUpdate",
        tag="settings",
        cli_name="put-settingname-jsonvalueupdate",
        summary="Set sub-value",
        path_params=('SettingName',),
        query_params=(),
        mutating=True,
    ),
    "statistics__delete-usage": Operation(
        id="statistics__delete-usage",
        method="DELETE",
        path="/api/statistics/usage",
        tag="statistics",
        cli_name="delete-usage",
        summary="Resets statistics cache",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "statistics__get-usage": Operation(
        id="statistics__get-usage",
        method="GET",
        path="/api/statistics/usage",
        tag="statistics",
        cli_name="get-usage",
        summary="Get statistics",
        path_params=(),
        query_params=('force',),
        mutating=False,
    ),
    "statistics__post-usage": Operation(
        id="statistics__post-usage",
        method="POST",
        path="/api/statistics/usage",
        tag="statistics",
        cli_name="post-usage",
        summary="Publsh statistics",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "system__get-fppd-restart": Operation(
        id="system__get-fppd-restart",
        method="GET",
        path="/api/system/fppd/restart",
        tag="system",
        cli_name="get-fppd-restart",
        summary="Restart fppd process",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__post-fppd-skipbootdelay": Operation(
        id="system__post-fppd-skipbootdelay",
        method="POST",
        path="/api/system/fppd/skipBootDelay",
        tag="system",
        cli_name="post-fppd-skipbootdelay",
        summary="Skip boot delay",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "system__get-fppd-start": Operation(
        id="system__get-fppd-start",
        method="GET",
        path="/api/system/fppd/start",
        tag="system",
        cli_name="get-fppd-start",
        summary="Start fppd",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-fppd-stop": Operation(
        id="system__get-fppd-stop",
        method="GET",
        path="/api/system/fppd/stop",
        tag="system",
        cli_name="get-fppd-stop",
        summary="Stop fppd",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-info": Operation(
        id="system__get-info",
        method="GET",
        path="/api/system/info",
        tag="system",
        cli_name="get-info",
        summary="Get system info",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-packages": Operation(
        id="system__get-packages",
        method="GET",
        path="/api/system/packages",
        tag="system",
        cli_name="get-packages",
        summary="Get all system packages",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-packages-info-packagename": Operation(
        id="system__get-packages-info-packagename",
        method="GET",
        path="/api/system/packages/info/{packageName}",
        tag="system",
        cli_name="get-packages-info-packagename",
        summary="Get system package information",
        path_params=('packageName',),
        query_params=(),
        mutating=False,
    ),
    "system__get-reboot": Operation(
        id="system__get-reboot",
        method="GET",
        path="/api/system/reboot",
        tag="system",
        cli_name="get-reboot",
        summary="Reboot the operating system",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-releasenotes-version": Operation(
        id="system__get-releasenotes-version",
        method="GET",
        path="/api/system/releaseNotes/{version}",
        tag="system",
        cli_name="get-releasenotes-version",
        summary="Get release notes",
        path_params=('version',),
        query_params=(),
        mutating=False,
    ),
    "system__get-shutdown": Operation(
        id="system__get-shutdown",
        method="GET",
        path="/api/system/shutdown",
        tag="system",
        cli_name="get-shutdown",
        summary="Shutdown the operating system",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-status": Operation(
        id="system__get-status",
        method="GET",
        path="/api/system/status",
        tag="system",
        cli_name="get-status",
        summary="Get system status",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-updatestatus": Operation(
        id="system__get-updatestatus",
        method="GET",
        path="/api/system/updateStatus",
        tag="system",
        cli_name="get-updatestatus",
        summary="Get fpp upgrade status",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__get-volume": Operation(
        id="system__get-volume",
        method="GET",
        path="/api/system/volume",
        tag="system",
        cli_name="get-volume",
        summary="Get volume",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "system__post-volume": Operation(
        id="system__post-volume",
        method="POST",
        path="/api/system/volume",
        tag="system",
        cli_name="post-volume",
        summary="Set volume",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "testmode__get-testmode": Operation(
        id="testmode__get-testmode",
        method="GET",
        path="/api/testmode",
        tag="testmode",
        cli_name="get-testmode",
        summary="Get Test Mode state",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
    "testmode__post-testmode": Operation(
        id="testmode__post-testmode",
        method="POST",
        path="/api/testmode",
        tag="testmode",
        cli_name="post-testmode",
        summary="Set Test Mode configuration",
        path_params=(),
        query_params=(),
        mutating=True,
    ),
    "time__get-time": Operation(
        id="time__get-time",
        method="GET",
        path="/api/time",
        tag="time",
        cli_name="get-time",
        summary="Get current time",
        path_params=(),
        query_params=(),
        mutating=False,
    ),
}


def _build_path(template: str, path_values: dict[str, str]) -> str:
    """Substitute {param} and handle /** wildcards."""
    path = template
    if "/**" in path and "_wildcard" in path_values:
        wc = path_values["_wildcard"].lstrip("/")
        path = path.replace("/**", "/" + wc if wc else "")
    elif "/*" in path and "_tail" in path_values:
        tail = path_values["_tail"].lstrip("/")
        path = path.replace("/*", "/" + tail if tail else "")
    for key, val in path_values.items():
        if key.startswith("_"):
            continue
        path = path.replace("{" + key + "}", api.quote_segment(str(val)))
    return path


def execute(
    op_id: str,
    *,
    path_values: dict[str, str] | None = None,
    query: dict[str, Any] | None = None,
    body: Any | None = None,
    base_url: str | None = None,
) -> Any:
    """Execute a registered OpenAPI operation by id."""
    op = OPERATIONS[op_id]
    path_values = path_values or {}
    endpoint = _build_path(op.path, path_values)
    m = op.method
    if m == "GET":
        return api.api_get(endpoint, base_url=base_url, params=query)
    if m == "POST":
        return api.api_post(endpoint, body, base_url=base_url)
    if m == "PUT":
        return api.api_put(endpoint, body, base_url=base_url)
    if m == "DELETE":
        return api.api_delete(endpoint, base_url=base_url)
    if m == "PATCH":
        return api.api_request('PATCH', endpoint, base_url=base_url, json_data=body, params=query)
    raise ValueError(f"Unsupported method {m}")


def tags() -> list[str]:
    return sorted({op.tag for op in OPERATIONS.values()})


def ops_by_tag(tag: str) -> list[Operation]:
    return sorted([o for o in OPERATIONS.values() if o.tag == tag], key=lambda o: o.cli_name)